version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  redis-network:
    driver: bridge
